
package com.lhmh.client;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "Java6WS", targetNamespace = "http://server.lhmh.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface Java6WS {


    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "doSomething", targetNamespace = "http://server.lhmh.com/", className = "com.lhmh.client.DoSomething")
    @ResponseWrapper(localName = "doSomethingResponse", targetNamespace = "http://server.lhmh.com/", className = "com.lhmh.client.DoSomethingResponse")
    @Action(input = "http://server.lhmh.com/Java6WS/doSomethingRequest", output = "http://server.lhmh.com/Java6WS/doSomethingResponse")
    public String doSomething(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

}
