
package com.lhmh.client;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "Java6WSService", targetNamespace = "http://server.lhmh.com/", wsdlLocation = "http://127.0.0.1:8888/java6ws/Java6WS?wsdl")
public class Java6WSService
    extends Service
{

    private final static URL JAVA6WSSERVICE_WSDL_LOCATION;
    private final static WebServiceException JAVA6WSSERVICE_EXCEPTION;
    private final static QName JAVA6WSSERVICE_QNAME = new QName("http://server.lhmh.com/", "Java6WSService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://127.0.0.1:8888/java6ws/Java6WS?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        JAVA6WSSERVICE_WSDL_LOCATION = url;
        JAVA6WSSERVICE_EXCEPTION = e;
    }

    public Java6WSService() {
        super(__getWsdlLocation(), JAVA6WSSERVICE_QNAME);
    }

    public Java6WSService(WebServiceFeature... features) {
        super(__getWsdlLocation(), JAVA6WSSERVICE_QNAME, features);
    }

    public Java6WSService(URL wsdlLocation) {
        super(wsdlLocation, JAVA6WSSERVICE_QNAME);
    }

    public Java6WSService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, JAVA6WSSERVICE_QNAME, features);
    }

    public Java6WSService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public Java6WSService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns Java6WS
     */
    @WebEndpoint(name = "Java6WSPort")
    public Java6WS getJava6WSPort() {
        return super.getPort(new QName("http://server.lhmh.com/", "Java6WSPort"), Java6WS.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns Java6WS
     */
    @WebEndpoint(name = "Java6WSPort")
    public Java6WS getJava6WSPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://server.lhmh.com/", "Java6WSPort"), Java6WS.class, features);
    }

    private static URL __getWsdlLocation() {
        if (JAVA6WSSERVICE_EXCEPTION!= null) {
            throw JAVA6WSSERVICE_EXCEPTION;
        }
        return JAVA6WSSERVICE_WSDL_LOCATION;
    }

}
